spring:
  application:
    name: cozinha

  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:amqps://voowobdz:oPXu8xSnc3nXS_GlD6QR2wg9nz1afCdY@jackal.rmq.cloudamqp.com/voowobdz}
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        cozinha.pedido.processamento: true
      percentiles:
        cozinha.pedido.processamento: 0.5, 0.95, 0.99

server:
  port: ${SERVER_PORT:9090}
  shutdown: graceful

spring.lifecycle.timeout-per-shutdown-phase: 30s
